### ISSUE TITLE
Execution of script 'Stack Exchange Timer' failed! StackExchange is not defined

### ISSUE THREAD

**Issue by mibac138** [TheIoTCrowd/StackPostTimer#5]
#### Browser name, version and operating system: 

Chrome 60 on Windows

#### StackTimer version:
 

0.3.0

#### Description:

Opened StackOverflow and this error appeared
```
ERROR: Execution of script 'Stack Exchange Timer' failed! StackExchange is not defined
(anonymous) @ VM111:3
```

#### Steps to reproduce:
Hard to say. Type a query to google and open a StackOverflow link. Not 100% reproducible

**Comment by TheIoTCrowd** [comment]
Finding this difficult to reproduce, so if you catch it happening, it'd be really helpful if you could post what you did. I'll let you know if I find the cause in the meantime, but marking this 'not reproduced' until I can figure out what the cause is.

Thanks for reporting!
